name       : drive
version    : 0.4.0
release    : 3
source     :
    - https://github.com/odeke-em/drive/archive/refs/tags/v0.4.0.tar.gz : 7a6445b54c6c13d0ddd8893ca02264211eeea68c7a0c7e9ccc6473f68af40a00
license    : Apache-2.0
component  : network.download
summary    : Google Drive client for the commandline
description: |
    Google Drive client for the commandline
extract    : no
networking : yes
builddeps  :
    - git
    - golang
environment: |
    export GO111MODULE=off
    export GOPATH=$workdir
setup      : |
    mkdir -p src/github.com/odeke-em/
    tar -xf $sources/v$version.tar.gz -C src/github.com/odeke-em/
    mv src/github.com/odeke-em/drive-$version src/github.com/odeke-em/drive
    mkdir {bin,pkg}
    # Install a bunch of deps that they don't declare until build
    go get github.com/cheggaaa/pb
    go get github.com/go-martini/martini
    go get github.com/martini-contrib/binding
    go get github.com/mattn/go-isatty
    go get github.com/odeke-em/cache
    go get github.com/odeke-em/cli-spinner
    go get github.com/odeke-em/drive/cmd/drive
    go get github.com/odeke-em/drive/config
    go get github.com/odeke-em/drive-gen
    go get github.com/odeke-em/exponential-backoff
    go get github.com/odeke-em/go-utils/tmpfile
    go get github.com/odeke-em/log
    go get github.com/odeke-em/pretty-words
    go get github.com/odeke-em/semalim
    go get github.com/odeke-em/statos
    go get github.com/odeke-em/rsc/qr
    go get github.com/skratchdot/open-golang/open
    go get golang.org/x/crypto/scrypt
    go get golang.org/x/net/context
    go get golang.org/x/oauth2
    go get golang.org/x/oauth2/google
    go get google.golang.org/api/drive/v2
    go get google.golang.org/api/googleapi
build      : |
    cd src/github.com/odeke-em/drive
    %make linux
    cd drive-server
    go build -o ../bin/drive-server
install    : |
    install -dm00644 $installdir/usr/share/icons/hicolor/{128x128,scalable}/mimetypes
    cd src/github.com/odeke-em/drive
    install -Dm00755 bin/drive_linux $installdir/usr/bin/drive
    install -Dm00755 bin/drive-server $installdir/usr/bin/drive-server
    cp ./icons/*.png $installdir/usr/share/icons/hicolor/128x128/mimetypes/
    cp ./icons/*.svg $installdir/usr/share/icons/hicolor/scalable/mimetypes/
